language: ruby
script: bundle exec middleman build
env:
  global:
  - GIT_COMMITTER_NAME=Yuichiro Someya
  - GIT_COMMITTER_EMAIL=ayemos.y@gmail.com
  - GIT_AUTHOR_NAME=Yuichiro Someya
  - GIT_AUTHOR_EMAIL=ayemos.y@gmail.com
  - secure: 057P53SSIoaiGOSyG+BocRtUppT1LuA/tLvQZoMQK5nMCbJT5bRMe3O5olaer8jhda4kI0rnedDlA0YWI8b6M2/cbAh13XpJuhvagaepTQ+21mYS9S62i/6mDY15qLTWmU+PDRB1nR93I2wv8K1X8f1n10ecTRi8cEr3giGnJbYe9IYCW2dAadeud2N4hIAsJAYW3pMCRH9E/SrzwQIgqGmrpNF8lKAsn8ftQTxsKu9KkAlSufylzRbMIpIt6HMaRSantY3snAJMDgDxdQrn+o8ZPL+IN3DX4lCt+lffaWiKcOe/GRV/+zK+n/bKQskJv2OIsdqXuCQD1T387V1IzDMfIJQwgfGSVPsZ6JTpIBMuHyaiZVcBmMvk6yUE7nBu6qVtpvsT5CE97qW4Wq9chXvwTVkFA7rfKT53GedKNggTAuSBxvFE8LlDchi/lmMZIPrrxNJMTLhmWUN7P+7Tq09k+Gqg7Kd0dK6pjKMPNFmWwG2KDvFwwUZzrc1kUeNx5ejMsayjOHg/xfPtjutA3pbf/NX9oN+IetxUkdPV1iRBHhnUQDMK1SfHj0zadsLK3f+6IfGNWTNEbsM+zSRY6VQeQofc/QHJYFKg81BvYRwnMyrMz1+gLR5b28HAvEw6magPtvTlLNgyWkgpU0Y9MRO1w7K1DBl6Or6Oh997Cyg=
before_script:
- git clone --quiet https://github.com/ayemos/source.ayemos.github.io.git
- git clone --quiet https://github.com/ayemos/ayemos.github.io.git build
after_success:
- cd build
- git add -A
- git commit -m 'Update'
- '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/ayemos/ayemos.github.io.git master'
